"""Add category to Product

Revision ID: 959e0e181ca0
Revises: de277d1b0292
Create Date: 2024-11-22 14:37:20.151547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '959e0e181ca0'
down_revision = 'de277d1b0292'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
