"""Fix customer_link to customer_id

Revision ID: ed919e636411
Revises: da3ee1b8e972
Create Date: 2024-11-14 21:06:25.682192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed919e636411'
down_revision = 'da3ee1b8e972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_constraint('fk_wishlist_customer_id', type_='foreignkey')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_wishlist_customer_id', 'customer', ['customer_id'], ['id'])

    # ### end Alembic commands ###
